name: Main
on:
  push:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: https://spu-bf732509c06d4426913abc4cf91f6acf@spectral-us.checkpoint.com

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v2
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --ok --engines secrets,iac --include-tags base,audit,iac
